platform :ios, '8.0'
pod 'AFNetworking'
pod 'FMDB'
pod 'ReactiveCocoa'
pod 'Shimmer'
pod 'Masonry'
pod 'Mantle', '~>1.5.4'
pod 'BlocksKit'
pod 'PKRevealController'
pod 'DateTools'
pod 'NJKWebViewProgress'
pod 'SVWebViewController'
pod 'AFNetworking-RACExtensions'
pod 'RJBlurAlertView'
pod 'MBProgressHUD'
